apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd-config

commonAnnotations:
  "helm.sh/resource-policy": keep

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - accounts.ci="apiKey,login"
      - url="https://argocd.service.clee.private.morphacy.net"
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - redis.compression="gzip"
      - redis.server="argocd-redis:6379"
      - server.enable.gzip="true"
      - server.insecure="true"
  - name: argocd-rbac-cm
    behavior: merge
    literals:
      - |
        policy.csv=
          p, role:admin, applications, *, */*, allow
          p, role:ci, applications, get, *, allow
          p, role:ci, applications, sync, *, allow
          g, ci, role:ci

labels:
  - includeSelectors: true
    pairs:
      app: argocd
      managedBy: argocd
      managementCodeGroup: chrismlee42
      managementCodeProject: argocd-config

namespace: argocd

resources:
  # Determine latest stable version from https://github.com/argoproj/argo-cd/releases
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.1.8/manifests/install.yaml
  # - argocd-ingress.yaml
  - httproute.yaml
  - namespace.yaml
  # - tlsroute.yaml
